name: seating_plan
description: "A new Flutter project for managing and visualizing seating arrangements, providing an intuitive interface for creating, customizing, and optimizing seating plans for various events and occasions."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.8
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

